From Steven Thomas, "Subject: Collada fix There was a problem converting a file to Collada by using osgconv like this:
osgconv file.osg file.dae

You would get an error message:

I/O error : Permission denied
I/O error : Permission denied
error : xmlNewTextWriterFilename : out of memory!
Error: daeLIBXMLPlugin::write(file://cessna.dae) failed
Warning: Error in writing to "cessna.dae".

This was due to some bad URI processing code in the Collada plugin. The attached file fixes this by using the Collada DOM's URI processing functions. After this change the file will convert successfully in the local directory.
"


git-svn-id: http://svn.openscenegraph.org/osg/OpenSceneGraph/trunk@8314 16af8721-9629-0410-8352-f15c8da7e697